import { Radio, FileText, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';

/* ─── Workflow steps ─────────────────────────────────────────────────── */

const STEPS = [
  {
    num: '01',
    icon: Radio,
    title: 'Ingest structured signals',
    desc: 'Read-only integrations pull GitHub activity, meeting notes, documentation updates, API usage signals, and workflow records — the actual footprint of your engineering week.',
    tags: ['GitHub activity', 'Meeting notes', 'API signals', 'Doc updates'],
  },
  {
    num: '02',
    icon: FileText,
    title: 'Generate weekly summaries',
    desc: 'Authrix synthesizes ingested signals into a structured engineering summary — what shipped, what was discussed, where usage spiked. Generated by the system and explicitly marked as such.',
    tags: ['Synthesized', 'Structured output', 'Reviewable'],
  },
  {
    num: '03',
    icon: AlertCircle,
    title: 'Surface tasks and risk',
    desc: 'Follow-up tasks and operational risk are surfaced from each summary — rising API usage, unresolved action items from meeting notes, stale approval requests. Nothing acts automatically.',
    tags: ['Suggested tasks', 'Spend signals', 'Risk visibility'],
  },
  {
    num: '04',
    icon: CheckCircle2,
    title: 'Approve before execution',
    desc: 'External write actions enter an approval queue. A named person approves or denies. The decision, provenance, and outcome stay visible. No auto-approve path exists.',
    tags: ['Approval queue', 'Human decision', 'Visible outcome'],
  },
];

function StepCard({ step }: { step: typeof STEPS[number] }) {
  const [hovered, setHovered] = useState(false);

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="flex flex-col gap-6 p-8 cursor-default"
      style={{
        background: hovered
          ? 'color-mix(in srgb, var(--primary) 3%, var(--background))'
          : 'var(--background)',
        transition: 'background 0.2s',
      }}
    >
      {/* Number + icon row */}
      <div className="flex items-start justify-between">
        <span
          className="font-mono font-semibold select-none"
          style={{
            fontSize: '32px',
            lineHeight: 1,
            letterSpacing: '-0.04em',
            color: hovered
              ? 'color-mix(in srgb, var(--primary) 50%, var(--border))'
              : 'var(--border)',
            transition: 'color 0.2s',
          }}
        >
          {step.num}
        </span>
        <div
          className="size-9 flex items-center justify-center rounded shrink-0"
          style={{ background: 'var(--muted)', border: '1px solid var(--border)' }}
        >
          <step.icon
            className="size-4 transition-colors duration-200"
            style={{ color: hovered ? 'var(--primary)' : 'var(--muted-foreground)' }}
            strokeWidth={1.5}
          />
        </div>
      </div>

      {/* Text */}
      <div className="flex flex-col gap-3 flex-1">
        <h3 className="text-base font-semibold text-foreground" style={{ lineHeight: 1.3 }}>
          {step.title}
        </h3>
        <p className="text-sm text-muted-foreground leading-relaxed flex-1">
          {step.desc}
        </p>

        {/* Tags */}
        <div
          className="flex flex-wrap gap-1.5 pt-4"
          style={{ borderTop: '1px solid var(--border)' }}
        >
          {step.tags.map(tag => (
            <span
              key={tag}
              className="text-[10px] font-mono text-muted-foreground px-2 py-1 rounded"
              style={{ background: 'var(--muted)', border: '1px solid var(--border)' }}
            >
              {tag}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ─── Role cards ─────────────────────────────────────────────────────── */

/**
 * Top-down crab illustration. Each role gets a small symbolic detail
 * etched into the carapace — circuit nodes, document, cycle arrows, or
 * server bars — so they're distinct without being cartoonish.
 */
function CrabIcon({ detail, color }: { detail: 'circuit' | 'doc' | 'cycle' | 'server'; color: string }) {
  return (
    <svg
      viewBox="0 0 90 68"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      style={{ width: '100%', height: '100%', color }}
    >
      {/* ── Carapace (main body) ── */}
      <ellipse cx="45" cy="40" rx="22" ry="16" stroke="currentColor" strokeWidth="1.5" />

      {/* ── Rostrum (front V-notch) ── */}
      <path d="M37 24 L45 17 L53 24" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" fill="none" />

      {/* ── Eye stalks + eyes ── */}
      <line x1="37" y1="25" x2="31" y2="18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <circle cx="29.5" cy="16.5" r="2.5" fill="currentColor" />
      <line x1="53" y1="25" x2="59" y2="18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <circle cx="60.5" cy="16.5" r="2.5" fill="currentColor" />

      {/* ── Left cheliped (claw arm + pincer) ── */}
      <line x1="23" y1="33" x2="11" y2="26" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="11" y1="26" x2="5"  y2="22" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="11" y1="26" x2="8"  y2="30" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />

      {/* ── Right cheliped ── */}
      <line x1="67" y1="33" x2="79" y2="26" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="79" y1="26" x2="85" y2="22" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="79" y1="26" x2="82" y2="30" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />

      {/* ── Left walking legs (3) ── */}
      <line x1="24" y1="37" x2="8"  y2="36" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="23" y1="42" x2="7"  y2="44" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="24" y1="47" x2="10" y2="53" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />

      {/* ── Right walking legs (3) ── */}
      <line x1="66" y1="37" x2="82" y2="36" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="67" y1="42" x2="83" y2="44" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="66" y1="47" x2="80" y2="53" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />

      {/* ── Role-specific shell detail ── */}
      {detail === 'circuit' && (
        <>
          <circle cx="45" cy="38" r="1.8" fill="currentColor" opacity="0.7" />
          <circle cx="40" cy="45" r="1.8" fill="currentColor" opacity="0.7" />
          <circle cx="50" cy="45" r="1.8" fill="currentColor" opacity="0.7" />
          <line x1="45" y1="38" x2="40" y2="45" stroke="currentColor" strokeWidth="0.9" opacity="0.5" />
          <line x1="45" y1="38" x2="50" y2="45" stroke="currentColor" strokeWidth="0.9" opacity="0.5" />
          <line x1="40" y1="45" x2="50" y2="45" stroke="currentColor" strokeWidth="0.9" opacity="0.5" />
        </>
      )}
      {detail === 'doc' && (
        <>
          <rect x="39.5" y="33" width="11" height="14" rx="1.5" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" />
          <line x1="42" y1="37.5" x2="48" y2="37.5" stroke="currentColor" strokeWidth="0.9" opacity="0.65" />
          <line x1="42" y1="40.5" x2="48" y2="40.5" stroke="currentColor" strokeWidth="0.9" opacity="0.65" />
          <line x1="42" y1="43.5" x2="46" y2="43.5" stroke="currentColor" strokeWidth="0.9" opacity="0.65" />
        </>
      )}
      {detail === 'cycle' && (
        <>
          <path d="M40 35 L50 35 M47.5 33 L50 35 L47.5 37" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" strokeLinecap="round" strokeLinejoin="round" />
          <path d="M50 45 L40 45 M42.5 43 L40 45 L42.5 47" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" strokeLinecap="round" strokeLinejoin="round" />
        </>
      )}
      {detail === 'server' && (
        <>
          <rect x="38" y="33"   width="14" height="4" rx="0.75" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" />
          <rect x="38" y="39"   width="14" height="4" rx="0.75" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" />
          <rect x="38" y="45"   width="14" height="4" rx="0.75" stroke="currentColor" strokeWidth="0.9" fill="none" opacity="0.65" />
          <circle cx="49.5" cy="35" r="1"  fill="currentColor" opacity="0.6" />
          <circle cx="49.5" cy="41" r="1"  fill="currentColor" opacity="0.6" />
          <circle cx="49.5" cy="47" r="1"  fill="currentColor" opacity="0.6" />
        </>
      )}
    </svg>
  );
}

const ROLES = [
  {
    detail: 'circuit' as const,
    role: 'Engineer',
    sub: 'Code and architecture',
    desc: 'See your merged PRs, standup commitments, and usage spikes in one structured view. Know what shipped, what drifted, and what needs your attention — before it becomes a problem.',
    tags: ['GitHub', 'CI signals', 'Standup notes'],
    accent: false,
  },
  {
    detail: 'doc' as const,
    role: 'Docs',
    sub: 'Records and decisions',
    desc: 'Turn meeting notes, ADRs, and async decisions into a searchable, auditable record. Nothing disappears into a Slack thread. The history of what was agreed stays intact.',
    tags: ['Meeting notes', 'ADRs', 'Decision log'],
    accent: false,
  },
  {
    detail: 'cycle' as const,
    role: 'Workflow',
    sub: 'Ownership and follow-through',
    desc: "Stale follow-up items, missing owners, and unresolved decisions from standup and meeting records get surfaced every week. Assignments stay visible. Blocking approvals don't disappear into a thread.",
    tags: ['Missing owners', 'Stale follow-up', 'Blocking approvals'],
    accent: true,
  },
  {
    detail: 'server' as const,
    role: 'DevOps',
    sub: 'Posture and spend',
    desc: 'API usage trends, deployment signals, and infrastructure events flow into the same structured summary. Anomalies get surfaced before they become incidents or budget overruns.',
    tags: ['Usage posture', 'Deployment health', 'Budget drift'],
    accent: false,
  },
];

function RoleCard({ role }: { role: typeof ROLES[number] }) {
  const [hovered, setHovered] = useState(false);

  const iconColor = role.accent
    ? '#F97316'
    : hovered
      ? '#F97316'
      : 'var(--muted-foreground)';

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="relative flex flex-col gap-5 p-7 rounded-xl cursor-default overflow-hidden"
      style={{
        background: role.accent
          ? 'color-mix(in srgb, var(--primary) 6%, var(--muted))'
          : hovered
            ? 'color-mix(in srgb, var(--primary) 3%, var(--muted))'
            : 'var(--muted)',
        border: role.accent
          ? '1px solid color-mix(in srgb, var(--primary) 35%, transparent)'
          : `1px solid ${hovered ? 'color-mix(in srgb, var(--primary) 18%, var(--border))' : 'var(--border)'}`,
        transition: 'background 0.25s, border-color 0.25s',
      }}
    >
      {/* Top-edge glow on accent card */}
      {role.accent && (
        <div
          className="absolute inset-x-0 top-0 h-px"
          style={{ background: 'linear-gradient(90deg, transparent, var(--primary), transparent)' }}
        />
      )}

      {/* Crab illustration */}
      <div
        className="w-full"
        style={{
          aspectRatio: '90 / 68',
          transition: 'opacity 0.25s',
          opacity: hovered || role.accent ? 1 : 0.55,
        }}
      >
        <CrabIcon detail={role.detail} color={iconColor} />
      </div>

      {/* Role label */}
      <div className="flex flex-col gap-1">
        <h3
          className="font-semibold text-foreground"
          style={{ fontSize: '1.05rem', lineHeight: 1.2, letterSpacing: '-0.015em' }}
        >
          {role.role}
        </h3>
        <p
          className="font-mono uppercase text-muted-foreground"
          style={{ fontSize: '9px', letterSpacing: '0.12em' }}
        >
          {role.sub}
        </p>
      </div>

      <p className="text-sm text-muted-foreground leading-relaxed flex-1">
        {role.desc}
      </p>

      {/* Tags */}
      <div
        className="flex flex-wrap gap-1.5 pt-4"
        style={{
          borderTop: `1px solid ${role.accent
            ? 'color-mix(in srgb, var(--primary) 20%, var(--border))'
            : 'var(--border)'}`,
        }}
      >
        {role.tags.map(tag => (
          <span
            key={tag}
            className="text-[10px] font-mono px-2 py-1 rounded"
            style={{
              background: role.accent
                ? 'color-mix(in srgb, var(--primary) 10%, var(--background))'
                : 'var(--background)',
              border: role.accent
                ? '1px solid color-mix(in srgb, var(--primary) 25%, transparent)'
                : '1px solid var(--border)',
              color: role.accent ? 'var(--primary)' : 'var(--muted-foreground)',
            }}
          >
            {tag}
          </span>
        ))}
      </div>
    </div>
  );
}

/* ─── Section ────────────────────────────────────────────────────────── */

export function WorkflowSection() {
  return (
    <section
      id="workflow"
      className="py-28 px-6 bg-background"
      style={{ fontFamily: 'Inter, sans-serif' }}
    >
      <div className="max-w-7xl mx-auto">

        {/* ── Part 1: How it works ── */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-20">
          <div className="lg:col-span-5">
            <div className="text-[10px] font-mono uppercase tracking-widest text-primary mb-5">
              How it works
            </div>
            <h2
              className="font-semibold text-foreground"
              style={{ fontSize: 'clamp(1.6rem, 2.6vw, 2.4rem)', lineHeight: 1.2, letterSpacing: '-0.02em' }}
            >
              From signal to reviewable action in four steps
            </h2>
          </div>
          <div className="lg:col-span-6 lg:col-start-7 flex items-end">
            <p className="text-muted-foreground leading-relaxed" style={{ fontSize: '15px' }}>
              Signals are ingested, synthesized, and surfaced as recommendations.
              Humans decide what acts. Every stage is structured,
              transparent, and keeps the approval record intact.
            </p>
          </div>
        </div>

        {/* Steps grid */}
        <div
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-px"
          style={{ background: 'var(--border)' }}
        >
          {STEPS.map(step => (
            <StepCard key={step.num} step={step} />
          ))}
        </div>

        {/* ── Divider ── */}
        <div
          className="my-24"
          style={{
            height: '1px',
            background: 'linear-gradient(90deg, transparent, var(--border) 20%, var(--border) 80%, transparent)',
          }}
        />

        {/* ── Part 2: Four specialist roles ── */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-14">
          <div className="lg:col-span-5">
            <div className="text-[10px] font-mono uppercase tracking-widest text-primary mb-5">
              Four specialist roles
            </div>
            <h2
              className="font-semibold text-foreground"
              style={{ fontSize: 'clamp(1.6rem, 2.6vw, 2.4rem)', lineHeight: 1.2, letterSpacing: '-0.02em' }}
            >
              One workspace,{' '}
              <span style={{ color: 'var(--primary)' }}>four distinct</span>{' '}
              points of view.
            </h2>
          </div>
          <div className="lg:col-span-6 lg:col-start-7 flex items-end">
            <p className="text-muted-foreground leading-relaxed" style={{ fontSize: '15px' }}>
              Each role gets the operating view they actually need — the same underlying
              record, presented for different kinds of work.
            </p>
          </div>
        </div>

        {/* Roles grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {ROLES.map(role => (
            <RoleCard key={role.role} role={role} />
          ))}
        </div>

      </div>
    </section>
  );
}